PHPUnit Started (PHPUnit 10.5.46 using PHP 8.2.12 (cli) on WINNT)
Test Runner Configured
Bootstrap Finished (C:\laravel-apps\shipping-app\packages\Quitenoisemaker\ShippingTracker\vendor/autoload.php)
Data Provider Method Called (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::webhookProvider for test method Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_handles_webhook_and_stores_it)
Test Triggered PHPUnit Deprecation (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_handles_webhook_and_stores_it)
Data Provider method Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::webhookProvider() is not static
Data Provider Method Finished for Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_handles_webhook_and_stores_it:
- Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::webhookProvider
Test Suite Loaded (26 tests)
Event Facade Sealed
Test Runner Started
Test Suite Sorted
Test Runner Execution Started (26 tests)
Test Suite Started (C:\laravel-apps\shipping-app\packages\Quitenoisemaker\ShippingTracker\phpunit.xml, 26 tests)
Test Suite Started (ShippingTracker, 26 tests)
Test Suite Started (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest, 2 tests)
Before First Test Method Called (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::setUpBeforeClass)
Before First Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::setUpBeforeClass
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::it_tracks_shipment_successfully)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::it_tracks_shipment_successfully)
Assertion Succeeded (Constraint: is identical to '101782511', Value: '101782511')
Assertion Succeeded (Constraint: is identical to 'in_transit', Value: 'in_transit')
Assertion Succeeded (Constraint: is identical to 'Package', Value: 'Package')
Assertion Succeeded (Constraint: is identical to Array &0 [], Value: Array &0 [])
Test Passed (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::it_tracks_shipment_successfully)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::it_tracks_shipment_successfully)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::it_throws_exception_for_failed_tracking)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::it_throws_exception_for_failed_tracking)
Assertion Succeeded (Constraint: exception of type "Quitenoisemaker\ShippingTracker\Exceptions\ShippingException", Value: {enable export of objects to see this value})
Assertion Succeeded (Constraint: exception message contains 'Cargoplug tracking failed: Invalid tracking number', Value: 'Cargoplug tracking failed: Invalid tracking number')
Test Passed (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::it_throws_exception_for_failed_tracking)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::it_throws_exception_for_failed_tracking)
After Last Test Method Called (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::tearDownAfterClass)
After Last Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest::tearDownAfterClass
Test Suite Finished (Quitenoisemaker\ShippingTracker\Tests\CargoplugShippingProviderTest, 2 tests)
Test Suite Started (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest, 2 tests)
Before First Test Method Called (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::setUpBeforeClass)
Before First Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::setUpBeforeClass
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::it_handles_webhook_for_valid_payload)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::it_handles_webhook_for_valid_payload)
Assertion Succeeded (Constraint: {"tracking_number":"101782511","provider":"sendbox","status":"delivered"}, Value: 'shipments')
Assertion Succeeded (Constraint: {"tracking_number":"101782511","provider":"cargoplug","status":"delivered"}, Value: 'shipments')
Test Passed (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::it_handles_webhook_for_valid_payload)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::it_handles_webhook_for_valid_payload)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::it_logs_warning_for_invalid_provider)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::it_logs_warning_for_invalid_provider)
Assertion Succeeded (Constraint: is true, Value: true)
Test Passed (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::it_logs_warning_for_invalid_provider)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::it_logs_warning_for_invalid_provider)
After Last Test Method Called (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::tearDownAfterClass)
After Last Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest::tearDownAfterClass
Test Suite Finished (Quitenoisemaker\ShippingTracker\Tests\HandleShippingWebhookTest, 2 tests)
Test Suite Started (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest, 7 tests)
Before First Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUpBeforeClass)
Before First Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUpBeforeClass
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_throws_exception_for_missing_config)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_throws_exception_for_missing_config)
Assertion Succeeded (Constraint: exception of type "Quitenoisemaker\ShippingTracker\Exceptions\ShippingException", Value: {enable export of objects to see this value})
Assertion Succeeded (Constraint: exception message contains 'Sendbox base URL is not configured.', Value: 'Sendbox base URL is not configured.')
Test Passed (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_throws_exception_for_missing_config)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_throws_exception_for_missing_config)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_refreshes_access_token)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_refreshes_access_token)
Assertion Succeeded (Constraint: is identical to 'new-token', Value: 'new-token')
Assertion Succeeded (Constraint: is identical to 'new-token', Value: 'new-token')
Test Passed (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_refreshes_access_token)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_refreshes_access_token)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_throws_exception_for_failed_token_refresh)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_throws_exception_for_failed_token_refresh)
Assertion Succeeded (Constraint: exception of type "Quitenoisemaker\ShippingTracker\Exceptions\ShippingException", Value: {enable export of objects to see this value})
Assertion Succeeded (Constraint: exception message contains 'Failed to refresh Sendbox access token: Invalid credentials', Value: 'Failed to refresh Sendbox access token: Invalid credentials')
Test Passed (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_throws_exception_for_failed_token_refresh)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_throws_exception_for_failed_token_refresh)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_tracks_shipment_successfully)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_tracks_shipment_successfully)
Assertion Succeeded (Constraint: is identical to 'delivered', Value: 'delivered')
Assertion Succeeded (Constraint: is identical to Array &0 [], Value: Array &0 [])
Test Passed (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_tracks_shipment_successfully)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_tracks_shipment_successfully)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_throws_exception_for_invalid_tracking_number)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_throws_exception_for_invalid_tracking_number)
Assertion Succeeded (Constraint: exception of type "Quitenoisemaker\ShippingTracker\Exceptions\ShippingException", Value: {enable export of objects to see this value})
Assertion Succeeded (Constraint: exception message contains 'Sendbox tracking failed: Invalid tracking number', Value: 'Sendbox tracking failed: Invalid tracking number')
Test Passed (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_throws_exception_for_invalid_tracking_number)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_throws_exception_for_invalid_tracking_number)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_handles_valid_webhook)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_handles_valid_webhook)
Test Passed (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_handles_valid_webhook)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_handles_valid_webhook)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_logs_warning_for_invalid_webhook)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_logs_warning_for_invalid_webhook)
Test Passed (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_logs_warning_for_invalid_webhook)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::it_logs_warning_for_invalid_webhook)
After Last Test Method Called (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDownAfterClass)
After Last Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest::tearDownAfterClass
Test Suite Finished (Quitenoisemaker\ShippingTracker\Tests\SendboxShippingProviderTest, 7 tests)
Test Suite Started (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest, 7 tests)
Before First Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUpBeforeClass)
Before First Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUpBeforeClass
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_uses_default_provider)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_uses_default_provider)
Assertion Succeeded (Constraint: is an instance of class Quitenoisemaker\ShippingTracker\Providers\CargoplugShippingProvider, Value: {enable export of objects to see this value})
Test Passed (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_uses_default_provider)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_uses_default_provider)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_switches_provider_with_use_method)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_switches_provider_with_use_method)
Assertion Succeeded (Constraint: is an instance of class Quitenoisemaker\ShippingTracker\Providers\SendboxShippingProvider, Value: {enable export of objects to see this value})
Assertion Succeeded (Constraint: is an instance of class Quitenoisemaker\ShippingTracker\Providers\CargoplugShippingProvider, Value: {enable export of objects to see this value})
Test Passed (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_switches_provider_with_use_method)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_switches_provider_with_use_method)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_throws_exception_for_invalid_provider)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_throws_exception_for_invalid_provider)
Assertion Succeeded (Constraint: exception of type "Exception", Value: {enable export of objects to see this value})
Assertion Succeeded (Constraint: exception message contains 'Shipping provider [invalid] not configured.', Value: 'Shipping provider [invalid] not configured.')
Test Passed (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_throws_exception_for_invalid_provider)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_throws_exception_for_invalid_provider)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_throws_exception_when_no_provider_supports_tracking_number)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_throws_exception_when_no_provider_supports_tracking_number)
Assertion Succeeded (Constraint: exception of type "Quitenoisemaker\ShippingTracker\Exceptions\ShippingException", Value: {enable export of objects to see this value})
Assertion Succeeded (Constraint: exception message matches '/Failed to initialize provider/', Value: 'Failed to initialize provider [sendbox]: Sendbox base URL is not configured.')
Test Passed (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_throws_exception_when_no_provider_supports_tracking_number)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_throws_exception_when_no_provider_supports_tracking_number)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_tracks_multiple_shipments)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_tracks_multiple_shipments)
Assertion Succeeded (Constraint: is identical to 'in_transit', Value: 'in_transit')
Assertion Succeeded (Constraint: is identical to 'delivered', Value: 'delivered')
Test Passed (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_tracks_multiple_shipments)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_tracks_multiple_shipments)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_retrieves_shipment_history)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_retrieves_shipment_history)
Assertion Succeeded (Constraint: is identical to 'SB123', Value: 'SB123')
Assertion Succeeded (Constraint: is identical to 'delivered', Value: 'delivered')
Assertion Succeeded (Constraint: count matches 1, Value: Array &0 [
    0 => Array &1 [
        'description' => 'Delivered',
    ],
])
Test Passed (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_retrieves_shipment_history)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_retrieves_shipment_history)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_uses_cached_provider_for_known_tracking_number)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_uses_cached_provider_for_known_tracking_number)
Assertion Succeeded (Constraint: is identical to 'delivered', Value: 'delivered')
Assertion Succeeded (Constraint: is an instance of class Quitenoisemaker\ShippingTracker\Providers\SendboxShippingProvider, Value: {enable export of objects to see this value})
Test Passed (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_uses_cached_provider_for_known_tracking_number)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::it_uses_cached_provider_for_known_tracking_number)
After Last Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDownAfterClass)
After Last Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest::tearDownAfterClass
Test Suite Finished (Quitenoisemaker\ShippingTracker\Tests\ShippingTrackerTest, 7 tests)
Test Suite Started (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest, 2 tests)
Before First Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::setUpBeforeClass)
Before First Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::setUpBeforeClass
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::it_stores_webhook_with_correct_payload)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::it_stores_webhook_with_correct_payload)
Assertion Succeeded (Constraint: {"provider":"cargoplug","payload":"{\"tracking_number\":\"101782511\",\"status\":\"delivered\"}"}, Value: 'shipping_webhooks')
Assertion Succeeded (Constraint: is identical to Array &0 [
    'tracking_number' => '101782511',
    'status' => 'delivered',
], Value: Array &0 [
    'tracking_number' => '101782511',
    'status' => 'delivered',
])
Test Passed (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::it_stores_webhook_with_correct_payload)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::it_stores_webhook_with_correct_payload)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::it_casts_payload_to_array)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::it_casts_payload_to_array)
Assertion Succeeded (Constraint: is of type array, Value: Array &0 [
    'tracking_number' => '101782511',
    'status' => 'delivered',
])
Assertion Succeeded (Constraint: is identical to Array &0 [
    'tracking_number' => '101782511',
    'status' => 'delivered',
], Value: Array &0 [
    'tracking_number' => '101782511',
    'status' => 'delivered',
])
Test Passed (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::it_casts_payload_to_array)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::it_casts_payload_to_array)
After Last Test Method Called (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::tearDownAfterClass)
After Last Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest::tearDownAfterClass
Test Suite Finished (Quitenoisemaker\ShippingTracker\Tests\ShippingWebhookTest, 2 tests)
Test Suite Started (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest, 3 tests)
Before First Test Method Called (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::setUpBeforeClass)
Before First Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::setUpBeforeClass
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::it_formats_cargoplug_response)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::it_formats_cargoplug_response)
Assertion Succeeded (Constraint: is identical to 'CP123', Value: 'CP123')
Assertion Succeeded (Constraint: is identical to 'in_transit', Value: 'in_transit')
Assertion Succeeded (Constraint: is identical to 'Package', Value: 'Package')
Test Passed (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::it_formats_cargoplug_response)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::it_formats_cargoplug_response)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::it_throws_exception_for_empty_cargoplug_response)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::it_throws_exception_for_empty_cargoplug_response)
Assertion Succeeded (Constraint: exception of type "InvalidArgumentException", Value: {enable export of objects to see this value})
Assertion Succeeded (Constraint: exception message contains 'Cargoplug response data is empty', Value: 'Cargoplug response data is empty')
Test Passed (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::it_throws_exception_for_empty_cargoplug_response)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::it_throws_exception_for_empty_cargoplug_response)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::it_throws_exception_for_empty_sendbox_response)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::it_throws_exception_for_empty_sendbox_response)
Assertion Succeeded (Constraint: exception of type "InvalidArgumentException", Value: {enable export of objects to see this value})
Assertion Succeeded (Constraint: exception message contains 'Sendbox response data is empty', Value: 'Sendbox response data is empty')
Test Passed (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::it_throws_exception_for_empty_sendbox_response)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::it_throws_exception_for_empty_sendbox_response)
After Last Test Method Called (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::tearDownAfterClass)
After Last Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest::tearDownAfterClass
Test Suite Finished (Quitenoisemaker\ShippingTracker\Tests\TrackingResponseFormatterTest, 3 tests)
Test Suite Started (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest, 3 tests)
Before First Test Method Called (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::setUpBeforeClass)
Before First Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::setUpBeforeClass
Test Suite Started (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_handles_webhook_and_stores_it, 2 tests)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_handles_webhook_and_stores_it#Cargoplug)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_handles_webhook_and_stores_it#Cargoplug)
Assertion Succeeded (Constraint: is identical to 200, Value: 200, Message: Expected response status code [200] but received 200.)
Assertion Succeeded (Constraint: has the subset Array &0 [
    'message' => 'Webhook received',
], Value: Array &0 [
    'message' => 'Webhook received',
], Message: Unable to find JSON: 

[{
    "message": "Webhook received"
}]

within response JSON:

[{
    "message": "Webhook received"
}].

)
Assertion Succeeded (Constraint: {"provider":"cargoplug","payload":"{\"tracking_number\":\"101782511\",\"status\":\"delivered\"}"}, Value: 'shipping_webhooks')
Assertion Succeeded (Constraint: is true, Value: true, Message: The expected [Quitenoisemaker\ShippingTracker\Events\ShippingWebhookReceived] event was not dispatched.)
Test Passed (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_handles_webhook_and_stores_it#Cargoplug)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_handles_webhook_and_stores_it#Cargoplug)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_handles_webhook_and_stores_it#Sendbox)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_handles_webhook_and_stores_it#Sendbox)
Assertion Succeeded (Constraint: is identical to 200, Value: 200, Message: Expected response status code [200] but received 200.)
Assertion Succeeded (Constraint: has the subset Array &0 [
    'message' => 'Webhook received',
], Value: Array &0 [
    'message' => 'Webhook received',
], Message: Unable to find JSON: 

[{
    "message": "Webhook received"
}]

within response JSON:

[{
    "message": "Webhook received"
}].

)
Assertion Succeeded (Constraint: {"provider":"sendbox","payload":"{\"tracking_number\":\"101782511\",\"status\":\"delivered\"}"}, Value: 'shipping_webhooks')
Assertion Succeeded (Constraint: is true, Value: true, Message: The expected [Quitenoisemaker\ShippingTracker\Events\ShippingWebhookReceived] event was not dispatched.)
Test Passed (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_handles_webhook_and_stores_it#Sendbox)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_handles_webhook_and_stores_it#Sendbox)
Test Suite Finished (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_handles_webhook_and_stores_it, 2 tests)
Test Preparation Started (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_throws_exception_for_invalid_provider)
Before Test Method Called (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::setUp)
Before Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::setUp
Test Prepared (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_throws_exception_for_invalid_provider)
Assertion Succeeded (Constraint: is identical to 400, Value: 400, Message: Expected response status code [400] but received 400.)
Assertion Succeeded (Constraint: has the subset Array &0 [
    'message' => 'Invalid provider: invalid',
], Value: Array &0 [
    'message' => 'Invalid provider: invalid',
], Message: Unable to find JSON: 

[{
    "message": "Invalid provider: invalid"
}]

within response JSON:

[{
    "message": "Invalid provider: invalid"
}].

)
Test Passed (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_throws_exception_for_invalid_provider)
After Test Method Called (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::tearDown)
After Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::tearDown
Test Printed Unexpected Output


Test Finished (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::it_throws_exception_for_invalid_provider)
After Last Test Method Called (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::tearDownAfterClass)
After Last Test Method Finished:
- Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest::tearDownAfterClass
Test Suite Finished (Quitenoisemaker\ShippingTracker\Tests\WebhookControllerTest, 3 tests)
Test Suite Finished (ShippingTracker, 26 tests)
Test Suite Finished (C:\laravel-apps\shipping-app\packages\Quitenoisemaker\ShippingTracker\phpunit.xml, 26 tests)
Test Runner Execution Finished
Test Runner Finished
PHPUnit Finished (Shell Exit Code: 0)
